# Generated by Django 3.2.4 on 2021-06-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('tipo_parroquia', models.CharField(choices=[('urbana', 'Parroquia urbana'), ('rural', 'Parroquia rural')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BarrioCiudadela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('numero_vivienda', models.IntegerField(verbose_name='numero de viviendas')),
                ('parque', models.CharField(choices=[('1', 'numero 1'), ('2', 'numero 2'), ('3', 'numero 3'), ('4', 'numero 4'), ('5', 'numero 5'), ('6', 'numero 6')], max_length=30)),
                ('numero_edificios', models.IntegerField(verbose_name='numero de edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios_ciudadelas', to='ordenamiento.parroquia')),
            ],
        ),
    ]
