# Generated by Django 3.2.4 on 2021-06-19 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0003_auto_20210611_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('numero_vivienda', models.IntegerField(verbose_name='numero de viviendas')),
                ('parque', models.IntegerField(choices=[(1, '1 Parque'), (2, '2 Parques'), (3, '3 Parques'), (4, '4 Parques'), (5, '5 Parques'), (6, '6 Parques')])),
                ('numero_edificio', models.IntegerField(verbose_name='numero de edificios')),
            ],
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='tipo_parroquia',
            field=models.CharField(choices=[('urbana', 'Parroquia Urbana'), ('rural', 'Parroquia rural')], max_length=30),
        ),
        migrations.DeleteModel(
            name='BarrioCiudadela',
        ),
        migrations.AddField(
            model_name='barrio',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrio', to='ordenamiento.parroquia'),
        ),
    ]
